version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: 'JUnit4'
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: 'JUnit4-Vintage'
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: 'TestNG'
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
