name: "Dependabot Auto Approve and Merge"
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - TestNG

jobs:
  call-automerge:
    uses: flowlogix/base-pom/.github/workflows/dependabot-automerge.yml@main
    with:
      branches: 'main,TestNG'
    secrets:
      github-token: ${{ secrets.GH_AUTOMERGE_TOKEN }}
